networks:
  dev:

services:

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - dev