"""person can_be....

Revision ID: 48eba2b4dd78
Revises: c8af026d771b
Create Date: 2025-03-30 15:46:36.672972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48eba2b4dd78'
down_revision: Union[str, None] = 'c8af026d771b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('can_be_scheme_developer', sa.Boolean(), nullable=True))
    op.add_column('people', sa.Column('can_be_assembler', sa.Boolean(), nullable=True))
    op.add_column('people', sa.Column('can_be_programmer', sa.Boolean(), nullable=True))
    op.add_column('people', sa.Column('can_be_tester', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Update existing records
    op.execute("UPDATE people SET can_be_scheme_developer = FALSE WHERE can_be_scheme_developer IS NULL")
    op.execute("UPDATE people SET can_be_assembler = FALSE WHERE can_be_assembler IS NULL")
    op.execute("UPDATE people SET can_be_programmer = FALSE WHERE can_be_programmer IS NULL")
    op.execute("UPDATE people SET can_be_tester = FALSE WHERE can_be_tester IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'can_be_tester')
    op.drop_column('people', 'can_be_programmer')
    op.drop_column('people', 'can_be_assembler')
    op.drop_column('people', 'can_be_scheme_developer')
    # ### end Alembic commands ###
