"""counterparty....

Revision ID: 55351469196c
Revises: 48eba2b4dd78
Create Date: 2025-04-03 07:54:49.119561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55351469196c'
down_revision: Union[str, None] = '48eba2b4dd78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'can_be_scheme_developer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('people', 'can_be_assembler',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('people', 'can_be_programmer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('people', 'can_be_tester',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'can_be_tester',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('people', 'can_be_programmer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('people', 'can_be_assembler',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('people', 'can_be_scheme_developer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
