"""fix uuid

Revision ID: b14120ca8c92
Revises: 3598d21e418a
Create Date: 2025-03-22 03:20:46.432521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14120ca8c92'
down_revision: Union[str, None] = '3598d21e418a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'box_accounting', ['serial_num'])
    op.add_column('comments_on_orders', sa.Column('person_uuid', sa.UUID(), nullable=False))
    op.drop_constraint('comments_on_orders_person_id_fkey', 'comments_on_orders', type_='foreignkey')
    op.create_foreign_key(None, 'comments_on_orders', 'people', ['person_uuid'], ['uuid'])
    op.drop_column('comments_on_orders', 'person_id')
    op.create_unique_constraint(None, 'people', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.add_column('comments_on_orders', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments_on_orders', type_='foreignkey')
    op.create_foreign_key('comments_on_orders_person_id_fkey', 'comments_on_orders', 'people', ['person_id'], ['uuid'])
    op.drop_column('comments_on_orders', 'person_uuid')
    op.drop_constraint(None, 'box_accounting', type_='unique')
    # ### end Alembic commands ###
