"""edit task executor_uuid

Revision ID: da2746c002ab
Revises: 846b3b44c7df
Create Date: 2025-04-17 23:15:57.317397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2746c002ab'
down_revision: Union[str, None] = '846b3b44c7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executor_uuid', sa.UUID(), nullable=True))
    op.drop_constraint('tasks_executor_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'people', ['executor_uuid'], ['uuid'])
    op.drop_column('tasks', 'executor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_executor_id_fkey', 'tasks', 'people', ['executor_id'], ['uuid'])
    op.drop_column('tasks', 'executor_uuid')
    # ### end Alembic commands ###
