"""add user peson relationship

Revision ID: f57ffe7c2703
Revises: da2746c002ab
Create Date: 2025-05-04 12:45:10.491447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57ffe7c2703'
down_revision: Union[str, None] = 'da2746c002ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'people', ['user_id'])
    op.create_foreign_key(None, 'people', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'user_id')
    # ### end Alembic commands ###
